# Generated by Django 2.2.6 on 2019-10-14 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Temperatur',
            new_name='Temperature',
        ),
    ]
